Revert "Update AndroidX from build 13169796"
This reverts commit e17bb4be83e59d4c2b42f185c968e07edf094151.

Reason for revert: Caused java.lang.NoSuchMethodError b/402011984

Change-Id: I4b5df503f21400c32ce862940796b4575a40364d