Revert "Update AndroidX from build 11236508"
This reverts commit e5d632b87b3ff385f1fda42955277265420e6db9.

Reason for revert:`NoSuchMethodError` from androidx.wear.compose.material Chip (b/317178468)

Change-Id: Iaa9dc465f49b5f1886e52e78f97c58ad5a344a2d